[package]
name = "FunChain"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.132", features = ["derive"] }
sled = "0.34"
num-bigint = { version = "0.4", features = ["rand"] }
data-encoding = "2.9.0"